package agmed.gui;
import agmed.*;
import static agmed.gui.GerenciarCadastrosView.cbClienteList;
import java.util.ArrayList;
import java.util.List;

public class CadastrarClientesView extends javax.swing.JFrame {

    final static List<Cliente> clienteList = new ArrayList();
    private final static List<Cliente> auxList = new ArrayList();
    
    public CadastrarClientesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        CPF = new javax.swing.JLabel();
        Endereco = new javax.swing.JLabel();
        Contato = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfCPF = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfContato = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Nome.setText("Nome:");

        CPF.setText("CPF:");

        Endereco.setText("Endereço:");

        Contato.setText("Contato:");

        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeKeyReleased(evt);
            }
        });

        tfCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCPFKeyReleased(evt);
            }
        });

        tfEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEnderecoKeyReleased(evt);
            }
        });

        tfContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfContatoKeyReleased(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.setEnabled(false);
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(Contato))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Endereco, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CPF, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Nome, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfContato, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btCancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF)
                    .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Endereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contato))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Cliente pessoa = new Cliente(tfNome.getText(),tfCPF.getText(),
                tfEndereco.getText(),tfContato.getText());
        clienteList.add(pessoa);
        putClientesInCB();
        this.dispose();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tfContatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfContatoKeyReleased
        disableButton();
    }//GEN-LAST:event_tfContatoKeyReleased

    private void tfEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEnderecoKeyReleased
        disableButton();
    }//GEN-LAST:event_tfEnderecoKeyReleased

    private void tfCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCPFKeyReleased
        disableButton();
    }//GEN-LAST:event_tfCPFKeyReleased

    private void tfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyReleased
        disableButton();
    }//GEN-LAST:event_tfNomeKeyReleased
    
    public static List<Cliente> getClienteList(){
        return clienteList;
    }
       
    
    //esse metodo troca um cliente desaatualziado por um atualizado//
    public static void alteracaoFeita(Cliente c){

        for(int i = 0; i < clienteList.size(); i++){
            
            Cliente cliente = clienteList.get(i);
            
            if(cliente.getCPF().equals(c.getCPF())){
                auxList.add(cliente);
                auxList.add(c);
            }
        }
        
        validacaoDeAlteracao(auxList.get(0), auxList.get(1));
    }
         
    public static void validacaoDeAlteracao(Cliente cliente, Cliente c){
        int index = clienteList.indexOf(cliente);
        clienteList.remove(cliente);
        clienteList.add(index, c);
        putClientesInCB();
        auxList.clear();
    }
     
    public static void putClientesInCB(){
 
         cbClienteList.removeAllItems();
         for (CalendarioView cv: CadastrarMedicosView.agendas){ 
                cv.cbClienteList.removeAllItems();
            }
         
         for (Cliente c : CadastrarClientesView.getClienteList()) {
            
            GerenciarCadastrosView.addItems(c);
            
            for (CalendarioView cv: CadastrarMedicosView.agendas){
                cv.addItems(c);
            }
            GerenciarCadastrosView.clearInvestigados();
            
        }
        System.out.println(clienteList);
     }
    
    public static void putClientesInCB(Cliente c){

            for (CalendarioView cv: CadastrarMedicosView.agendas){
                cv.addItems(c);
            }
            GerenciarCadastrosView.addItems(c);
            clienteList.add(c);
 
    }
    
    public static void disableButton(){
        if(!(tfNome.getText().equals("") | tfCPF.getText().equals("")
                | tfEndereco.getText().equals("")
                | tfContato.getText().equals(""))){
            btCadastrar.setEnabled(true);
        }else{
            btCadastrar.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarClientesView().setVisible(true);
            }
            
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Contato;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel Nome;
    private static javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private static javax.swing.JTextField tfCPF;
    private static javax.swing.JTextField tfContato;
    private static javax.swing.JTextField tfEndereco;
    private static javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
