
package agmed.gui;

import agmed.Cliente;
import agmed.Medico;
import agmed.PessoaFisica;
import static agmed.gui.CadastrarMedicosView.alteracaoFeita;
import static agmed.gui.CadastrarClientesView.alteracaoFeita;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GerenciarCadastrosView extends javax.swing.JFrame {
    
    
    //Lista criada para gerenciar e vizualizar um objeto cadastrado no sistema//
     static List<PessoaFisica> investigados = new ArrayList();
    
    public GerenciarCadastrosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbMedicoList = new javax.swing.JComboBox<>();
        cbClienteList = new javax.swing.JComboBox<>();
        Medicos = new javax.swing.JLabel();
        Clientes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfPesquisar = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btOk1 = new javax.swing.JButton();
        btOk2 = new javax.swing.JButton();
        btDispensar = new javax.swing.JButton();

        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbMedicoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedicoListActionPerformed(evt);
            }
        });

        Medicos.setText("Médicos:");

        Clientes.setText("Clientes:");

        jLabel1.setText("Pesquisar");

        tfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisarActionPerformed(evt);
            }
        });

        btOk.setText("OK!");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btOk1.setText("OK!");
        btOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOk1ActionPerformed(evt);
            }
        });

        btOk2.setText("OK!");
        btOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOk2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Clientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btOk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbClienteList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Medicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btOk2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMedicoList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btOk)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOk))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMedicoList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOk2)
                    .addComponent(Medicos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbClienteList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOk1)
                    .addComponent(Clientes))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btDispensar.setText("Dispensar");
        btDispensar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDispensarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDispensar)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btDispensar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisarActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        
        String aux = tfPesquisar.getText();
        
        for(PessoaFisica p: CadastrarMedicosView.getMedicoList()){
                if(p.getNome().equals(tfPesquisar.getText())){
                    investigados.add(p);
                    AlterarPropriedadesMView tela = new AlterarPropriedadesMView();
                    tela.setVisible(true);
                    tfPesquisar.setText("");
                    break;
                }
            }
            for(PessoaFisica p: CadastrarClientesView.getClienteList()){
                if(p.getNome().equals(tfPesquisar.getText())){
                    investigados.add(p);
                    AlterarPropriedadesCView tela = new AlterarPropriedadesCView();
                    tela.setVisible(true);
                    tfPesquisar.setText("");
                    break;
                }
            }
            if(tfPesquisar.getText().equals(aux)){
                tfPesquisar.setText("Não encontrado!");
            }
            
    }//GEN-LAST:event_btOkActionPerformed

    private void btOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOk1ActionPerformed
        clearInvestigados();
        investigados.add(cbClienteList.getItemAt(cbClienteList.getSelectedIndex()));
        AlterarPropriedadesCView tela = new AlterarPropriedadesCView();
        tela.setVisible(true);
    }//GEN-LAST:event_btOk1ActionPerformed

    private void btOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOk2ActionPerformed
        clearInvestigados();
        investigados.add(cbMedicoList.getItemAt(cbMedicoList.getSelectedIndex()));
        AlterarPropriedadesMView tela = new AlterarPropriedadesMView();
        
        tela.setVisible(true);
    }//GEN-LAST:event_btOk2ActionPerformed

    private void cbMedicoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedicoListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMedicoListActionPerformed

    private void btDispensarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDispensarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btDispensarActionPerformed

    public static void addItems(Cliente o){
        cbClienteList.addItem(o);
    }
    
    public static void addItems(Medico o){
        cbMedicoList.addItem(o);
    }
    
    public static void clearInvestigados(){
        investigados.clear();
    }
    
    public static List getInvestigados(){
        return investigados;
    }
    
    public static void alteracoesSalvas(String con, String end, String espc, String fun){
            
        Medico m = (Medico)investigados.get(0);
        m.setContato(con);
        m.setEndereco(end);
        m.setEspc(espc);
        m.setFuncao(fun);
        clearInvestigados();
        for(int i = 0; i < CadastrarMedicosView.getMedicoList().size(); i++){
            Medico medico = CadastrarMedicosView.getMedicoList().get(i);
            if(medico.getCRM().equals(m.getCRM())){
                alteracaoFeita(medico);
            }
        }
    }
    
    public static void alteracoesSalvas(String con, String end){
        if(investigados.get(0) instanceof Cliente){
            Cliente c = (Cliente)investigados.get(0);
            c.setContato(con);
            c.setEndereco(end);
            clearInvestigados();
            for(int i = 0; i < CadastrarClientesView.getClienteList().size(); i++){
            Cliente cliente = CadastrarClientesView.getClienteList().get(i);
            if(cliente.getCPF().equals(c.getCPF())){
                alteracaoFeita(cliente);
            }
        }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarCadastrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarCadastrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarCadastrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarCadastrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarCadastrosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clientes;
    private javax.swing.JLabel Medicos;
    private javax.swing.JButton btDispensar;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btOk1;
    private javax.swing.JButton btOk2;
    static javax.swing.JComboBox<Cliente> cbClienteList;
    static javax.swing.JComboBox<Medico> cbMedicoList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfPesquisar;
    // End of variables declaration//GEN-END:variables
}
