/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agmed.gui;

import agmed.Cliente;
import static agmed.gui.CadastrarClientesView.clienteList;
import static agmed.gui.GerenciarCadastrosView.investigados;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author corin
 */
public class HistoricoMedicoView extends javax.swing.JFrame {

    /**
     * Creates new form HistoricoMedicoView
     */
    public HistoricoMedicoView() {
        initComponents();
        
        for (int i = 0; i < clienteList.size(); i++){
            if(clienteList.get(i).getCPF().equals(investigados.get(0).getCPF())){
                Cliente c = clienteList.get(i);
                taHM.setText(c.getHistoricoMedico());   
                System.out.println((investigados.get(0)));
            } 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRemoverEntrada = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfDia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        btNovaEntrada = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taHM = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btRemoverEntrada.setText("Remover Entrada");
        btRemoverEntrada.setEnabled(false);
        btRemoverEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverEntradaActionPerformed(evt);
            }
        });

        jLabel1.setText("Dia: (DDMMAAAA)");

        tfDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDiaKeyReleased(evt);
            }
        });

        jLabel2.setText("Hora:");

        tfHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfHoraKeyReleased(evt);
            }
        });

        jLabel3.setText("Descrição:");

        tfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDescricaoKeyReleased(evt);
            }
        });

        btNovaEntrada.setText("Nova Entrada");
        btNovaEntrada.setEnabled(false);
        btNovaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovaEntradaActionPerformed(evt);
            }
        });

        taHM.setColumns(20);
        taHM.setRows(5);
        taHM.setEnabled(false);
        jScrollPane2.setViewportView(taHM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btNovaEntrada))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfHora))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(btRemoverEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRemoverEntrada)
                    .addComponent(jLabel1)
                    .addComponent(tfDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btNovaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(tfDescricao))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovaEntradaActionPerformed

        int index = 0;
        
        for (int i = 0; i < clienteList.size(); i++){
            if(clienteList.get(i).getCPF().equals(investigados.get(0).getCPF())){
                Cliente c = clienteList.get(i);
                c.novaEntrada(tfDia.getText(),tfDescricao.getText(),tfHora.getText());
                System.out.println(c.historicoMedico);
                taHM.setText(c.getHistoricoMedico());
                index = i;
                
            } 
        }
        CadastrarClientesView.alteracaoFeita(clienteList.get(index));
        investigados.add(clienteList.get(index));
    }//GEN-LAST:event_btNovaEntradaActionPerformed

    private void btRemoverEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverEntradaActionPerformed
        
        int index = 0;
        
        for (int i = 0; i < clienteList.size(); i++){
            if(clienteList.get(i).getCPF().equals(investigados.get(0).getCPF())){
                Cliente c = clienteList.get(i);
                c.limparEntrada(tfDia.getText());
                System.out.println(c.historicoMedico);
                taHM.setText(c.getHistoricoMedico()); 
                index = i;
            }
        }
            CadastrarClientesView.alteracaoFeita(clienteList.get(index));
            investigados.add(clienteList.get(index));
    }//GEN-LAST:event_btRemoverEntradaActionPerformed

    private void tfDiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDiaKeyReleased
        disableButton();
        disableButtonR();
    }//GEN-LAST:event_tfDiaKeyReleased

    private void tfHoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHoraKeyReleased
        disableButton();
    }//GEN-LAST:event_tfHoraKeyReleased

    private void tfDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescricaoKeyReleased
        disableButton();
    }//GEN-LAST:event_tfDescricaoKeyReleased

    public static void disableButton(){
        if(!(tfDia.getText().equals("") | tfDescricao.getText().equals("")
                | tfHora.getText().equals(""))){
            btNovaEntrada.setEnabled(true);
        }else{
            btNovaEntrada.setEnabled(false);
        }
    }
    
        public static void disableButtonR(){
        if(!(tfDia.getText().equals(""))){
            btRemoverEntrada.setEnabled(true);
        }else{
            btRemoverEntrada.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoMedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoMedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoMedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoMedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoMedicoView().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btNovaEntrada;
    private static javax.swing.JButton btRemoverEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taHM;
    private static javax.swing.JTextField tfDescricao;
    private static javax.swing.JTextField tfDia;
    private static javax.swing.JTextField tfHora;
    // End of variables declaration//GEN-END:variables
}
