/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agmed.gui;

/**
 *
 * @author corin
 */
public class overView extends javax.swing.JFrame {

    /**
     * Creates new form overView
     */
    public overView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbMenuBar = new javax.swing.JMenuBar();
        meAgenda = new javax.swing.JMenu();
        miVizAgnedas = new javax.swing.JMenuItem();
        miAgendasArquivadas = new javax.swing.JMenuItem();
        meCadastro = new javax.swing.JMenu();
        miNvCliente = new javax.swing.JMenuItem();
        miNvMedico = new javax.swing.JMenuItem();
        miGerenCadastros = new javax.swing.JMenuItem();
        meLogin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meAgenda.setText("Agenda");

        miVizAgnedas.setText("Vizualizar agendas");
        miVizAgnedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVizAgnedasActionPerformed(evt);
            }
        });
        meAgenda.add(miVizAgnedas);

        miAgendasArquivadas.setText("Agendas Arquivadas");
        miAgendasArquivadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgendasArquivadasActionPerformed(evt);
            }
        });
        meAgenda.add(miAgendasArquivadas);

        mbMenuBar.add(meAgenda);

        meCadastro.setText("Cadastros");
        meCadastro.setToolTipText("");

        miNvCliente.setText("Novo cliente");
        miNvCliente.setMargin(new Insets(2, -20, 2, 2));
        meCadastro.add(miNvCliente);

        miNvMedico.setText("Novo médico");
        miNvMedico.setToolTipText("");
        meCadastro.add(miNvMedico);

        miGerenCadastros.setText("Gerenciar cadastros");
        miGerenCadastros.setToolTipText("");
        meCadastro.add(miGerenCadastros);

        mbMenuBar.add(meCadastro);

        meLogin.setText("Login");
        meLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mbMenuBar.add(meLogin);

        setJMenuBar(mbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAgendasArquivadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgendasArquivadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAgendasArquivadasActionPerformed

    private void miVizAgnedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVizAgnedasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miVizAgnedasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(overView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(overView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(overView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(overView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new overView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mbMenuBar;
    private javax.swing.JMenu meAgenda;
    private javax.swing.JMenu meCadastro;
    private javax.swing.JMenu meLogin;
    private javax.swing.JMenuItem miAgendasArquivadas;
    private javax.swing.JMenuItem miGerenCadastros;
    private javax.swing.JMenuItem miNvCliente;
    private javax.swing.JMenuItem miNvMedico;
    private javax.swing.JMenuItem miVizAgnedas;
    // End of variables declaration//GEN-END:variables
}
